name: build
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Run Tests

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Run Tests
        run: mvn --batch-mode --update-snapshots test
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'